# Generated by Django 4.1.1 on 2022-09-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=100)),
                ("ip", models.CharField(max_length=39, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("domain", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
